version: '3.9'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
      args:
        environment: dev
        status: stable
    restart: always
    container_name: react-front
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - front-net
  backend:
    build:
      context: ./backend
    restart: always
    container_name: fastapi-back
    volumes:
      - './backend:/app'
    ports:
      - 8000:8000
    networks:
      - front-net
networks:
  front-net: {}
